export const GET_PRODUCTS = 'GET_PRODUCTS';
export const NEW_PRODUCT = 'NEW_PRODUCT';
export const DELETE_PRODUCT = 'DELETE_PRODUCT';
export const ADD_PRODUCT_REVIEW = 'ADD_PRODUCT_REVIEW';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';