export const GET_PRODUCTS = 'GET_PRODUCTS';
export const NEW_PRODUCT = 'NEW_PRODUCT';
export const DELETE_PRODUCT = 'DELETE_PRODUCT';
export const EDIT_PRODUCT = 'EDIT_PRODUCT';

export const ADD_PRODUCT_REVIEW = 'ADD_PRODUCT_REVIEW';

export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const GET_USERS = 'GET_USERS';

export const GET_CATEGORIES = 'GET_CATEGORIES';

export const NEW_ORDER = 'NEW_ORDER';

export const GET_PROFILE = 'GET_PROFILE';
export const EDIT_PROFILE = 'EDIT_PROFILE';
export const CHANGE_USER_NAME = 'CHANGE_USER_NAME';
export const CHANGE_ADDRESS = 'CHANGE_ADDRESS';